### ISSUE TITLE
PLP package contains 3 versions of cohorts

### ISSUE THREAD

**Issue by pavgra** [OHDSI/Hydra#1]
Why does generated PLP package contain 3 versions of cohorts?

- One set of cohorts is built into `predictionAnalysisList.json`
- Another set is under `inst/sql/sql_server`
- The third one is in `inst/cohorts`

Why such redundancy is required? Often, redundancy causes anomalies and inconsistency, so there should be a single source of truth (if we are not talking about intended redundancy for purpose of data restoration).

**Comment by schuemie** [comment]
All our study packages have the JSON cohort definitions in `inst/cohorts` and the SQL cohort definitions in `inst/sql`. I agree it might not be ideal to have both, since they can run out of sync, but we currently have no ability to generate SQL from JSON in R. That being said, I do like the fact that the SQL is pre-generated, because now we don't have to worry about different versions of circe which could lead to different SQL being generated from the same JSON.

The third copy, in `predictionAnalysisList.json`, is unique to hydrated skeleton packages. It is simply a copy of the JSON used to hydrate the package.
